### ISSUE TITLE
Help wanted: Project needs CI/CD for popular OSes - configuring Github Actions

### ISSUE THREAD

**Issue by robertlipe** [pine64/blisp#30] opened 2023-03-31 23:42 UTC
To prevent quality regressions and to make snapshot images trivially available, blisp should be continually built for at least the three main OSes where it is used, preferably with at lesat some kind of a regression testsuite that doesnt require actual hardware.

Is anyone interested in looking at https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration and leading a charge of integrations? This proeject is small enough that we should trivially fit within the letter and spirit of the free usage levels. On my system the library build in under a second, so even if the rest of it build and it took as many as two seconds with regression testing adding five more, we should be able to get a LOT of builds in (even with multiple OSes) with a 2,000 minute budget.

There's not a lot of programming skills needed here. There are plenty of texamples on GitHub and various blogs on how to set this up.

Any volunteers?

**Comment by gamelaster** [comment] 2023-04-01 07:24
This is already done, and it compiles Windows, Linux and Mac: https://github.com/pine64/blisp/actions/runs/4567945677

**Comment by River-Mochi** [comment] 2023-04-01 08:10
confirmed,  people are using command line  Blisp to upgrade Pinecil V2 in  Windows, MacOS,  and Linux.  although windows users tend to have most difficulty as  powershell terminal is not something commonly used by  soldering iron owners.

Details  in BLISP  Wiki page here  on how it's installed for all 3 OS: https://github.com/pine64/blisp/wiki/Update-Pinecil-V2

 cute graphic I made here.  Is FreeBSD  that different that it gets it's own support line?
I simply converted the supported list into the table with icons and noticed FreeBSD listed.

![image](https://user-images.githubusercontent.com/97197236/229274078-6802c702-2b90-4514-8399-8e99e95ef67a.png)

**Comment by River-Mochi** [comment] 2023-04-01 08:13
Robert are you saying that   you are unable to use BLISP currently to  upgrade your V2 pinecil on MacOS?

- Check this out if it helps:  https://wiki.pine64.org/wiki/Pinecil_Firmware#Update_V2:_Linux_and_Mac
- and if  it still does not work,  then  go to Pinecil Chat and i'm sure someone knows something and could help.

**Comment by River-Mochi** [comment] 2023-04-02 04:57
would it be possible to package blisp in a way that it could be installed the way we can install dfu-util on the command line such as with    
`sudo pacman`

**Comment by StevenSeifried** [comment] 2023-04-02 09:44
blisp is now in the AUR. https://aur.archlinux.org/packages/blisp-bin

**Comment by River-Mochi** [comment] 2023-04-02 13:32
@robertlipe   for your mac  V2 udate, 
 If you just want to update it quickly, maybe just use the premade easy binary in releases if you are unable to build from code right now. 

 dont' want to assume basics,  but also make sure to  hold down the [-] button  before plugging the cable into the mac.  
I usually plug cable to PC first, then hold the (-) button, then plug into back of the Pinecil, keep holding (-)  for 10 seconds, then release.  after that   the pre-made  MacOS  exeutable binary  in releases  "should" theoretically work.

**Comment by River-Mochi** [comment] 2023-04-03 05:11
oic, sorry, I was confused.   you were trying to help @spagett1 get  an exit code since he is working on making blisp work better inside PineFlash

**Comment by Ralim** [comment] 2023-05-08 22:10
I'm going to close this issue as its not really on track to the original post.
There is CI enforcement for building for all three main OS's, and I have manually run a cmake build on all 3 now and could build the project fine.

**Closed by Ralim** 2023-05-08 22:10 UTC
Labels: help wanted, good first issue
